dataset:
  train_pos_img_path: E:\Projects\detection\INRIAPerson\96X160H96\Train\pos
  train_neg_img_path: E:\Projects\detection\INRIAPerson\Train\neg
  test_pos_img_path: E:\Projects\detection\INRIAPerson\70X134H96\Test\pos
  test_neg_img_path: E:\Projects\detection\INRIAPerson\Test\neg
  shuffle: True
  resize: [128, 64]

normalization:
  gamma: 0.5

hog: 
  gradient_operator: simple
  bins: 9
  interpolation: none
  cell_size: 8
  block_size: 2
  block_stride: 1
  norm_method: L2-Hys
  
svm:
  kernel: linear

train: 